set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 10000

set -g exit-empty on
set -g destroy-unattached on


unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf \; display "Config reloaded"

setw -g mode-keys emacs

set -g @catppuccin_flavor "mocha"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

run '/home/carlos/Repos/tmux-plugins/tpm/tpm'
