splash = false

wallpaper {
    monitor = eDP-1
    path = /home/carlos/Documents/02-Resources/Pictures/Wallpapers/black-white-wp.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/carlos/Documents/02-Resources/Pictures/Wallpapers/star-wp.png
    fit_mode = cover
}

# opcional: fallback para cualquier monitor nuevo/desconocido
wallpaper {
    monitor =
    path = /home/carlos/Documents/02-Resources/Pictures/Wallpapers/star-wp.png
    fit_mode = cover
}
