wallpaper {
    monitor = eDP-1
    path = /home/carlos/Pictures/Wallpapers/red.png
    fit_mode = cover
}

# opcional: fallback para cualquier monitor nuevo/desconocido
wallpaper {
    monitor =
    path = /home/carlos/Pictures/Wallpapers/cdlrwp.jpg
    fit_mode = cover
}
