wallpaper {
    monitor = eDP-1
    path = /home/carlos/Pictures/Wallpapers/02-2026.png
    fit_mode = cover
}

# opcional: fallback para cualquier monitor nuevo/desconocido
wallpaper {
    monitor =
    path = /home/carlos/Pictures/Wallpapers/02-2026.png
    fit_mode = cover
}
