[ids]

*

[main]

leftalt = layer(dia)
enter = noop

[dia]

space = enter
a = macro(compose apostrophe a)
e = macro(compose apostrophe e)
i = macro(compose apostrophe i)
o = macro(compose apostrophe o)
u = macro(compose apostrophe u)
n = macro(compose S-grave n)

[altgr]

space = enter
