configurations:
  - alias: gmail
    host: imap.gmail.com
    port: 993
    tls: true

    username: carlosjaragebhard@gmail.com
    password: "svodsynrnykzyozp"

    boxes:
      - mailbox: INBOX
        onNewMail: "mbsync gmail"

      - mailbox: "[Gmail]/Sent Mail"
        onNewMail: "mbsync gmail"

      - mailbox: "[Gmail]/Trash"
        onNewMail: "mbsync gmail"
